/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          foreground: 'var(--color-primary-foreground)',
          muted: 'var(--color-primary-muted)',
          50: '#f3f2ff',
          100: '#e9e7fd',
          200: '#d4d0fb',
          300: '#b9b2f8',
          400: '#8F85F3',
          500: '#7367F0',
          600: '#675DD8',
          700: '#5a52c4',
          800: '#4a44a3',
          900: '#3d3885',
        },
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: {
          DEFAULT: 'var(--color-card)',
          foreground: 'var(--color-card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--color-card)',
          foreground: 'var(--color-card-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          foreground: 'var(--color-secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--color-muted)',
          foreground: 'var(--color-muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--color-secondary)',
          foreground: 'var(--color-secondary-foreground)',
        },
        destructive: {
          DEFAULT: '#FF4C51',
          foreground: '#ffffff',
        },
        success: {
          DEFAULT: '#28C76F',
          foreground: '#ffffff',
        },
        warning: {
          DEFAULT: '#FF9F43',
          foreground: '#ffffff',
        },
        info: {
          DEFAULT: '#00BAD1',
          foreground: '#ffffff',
        },
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        'input-background': 'var(--color-input-background)',
        ring: 'var(--color-primary)',
        slate: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        chart: {
          1: '#7367F0',
          2: '#28C76F',
          3: '#FF9F43',
          4: '#8b5cf6',
          5: '#ec4899',
        },
      },
      borderRadius: {
        sm: 4,
        DEFAULT: 6,
        md: 6,
        lg: 8,
        xl: 12,
        '2xl': 16,
        '3xl': 24,
      },
      fontSize: {
        '2xs': 10,
        xs: 12,
        sm: 13,
        base: 14,
        md: 15,
        lg: 16,
        xl: 18,
        '2xl': 22,
        '3xl': 28,
        '4xl': 34,
      },
      spacing: {
        '0.5': 2,
        '1': 4,
        '1.5': 6,
        '2': 8,
        '2.5': 10,
        '3': 12,
        '3.5': 14,
        '4': 16,
        '5': 20,
        '6': 24,
        '7': 28,
        '8': 32,
        '9': 36,
        '10': 40,
        '11': 44,
        '12': 48,
        '14': 56,
        '16': 64,
        '20': 80,
        '24': 96,
      },
    },
  },
  plugins: [],
};
